[2023-09-08 12:02:12,513][main.py][line:301][INFO] total params:1.2091M
[2023-09-08 12:02:12,513][main.py][line:304][INFO] Training Mode
8000 8100 2900
[2023-09-08 12:02:17,264][main.py][line:163][INFO] Random initialize AUCAUC:0.4774 Anomaly AUC:0.48817
[2023-09-08 12:02:21,302][main.py][line:166][INFO] Random initialize AUCAUC:0.3413 Anomaly AUC:0.50247
Predict video 77 | num abnormal video:7:   1%|█▍                                                                                                                                                                 | 71/8100 [00:00<01:24, 95.32it/s]








































Predict video 7910 | num abnormal video:695:  98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏   | 7904/8100 [01:21<00:01, 161.89it/s]
num videos : 7140
num frames : 23336
Predict video 8100 | num abnormal video:713: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8100/8100 [01:22<00:00, 98.19it/s]
Traceback (most recent call last):
  File "/home/yukaneko/dev/AbnormalDetection/PEL4VAD/main.py", line 340, in <module>
    main(cfg)
  File "/home/yukaneko/dev/AbnormalDetection/PEL4VAD/main.py", line 306, in main
    train(pel_model, ur_model, train_nloader, train_aloader, test_loader, gt, logger)
  File "/home/yukaneko/dev/AbnormalDetection/PEL4VAD/main.py", line 176, in train
    print(len(train_anomaly_data.list))
AttributeError: 'Subset' object has no attribute 'list'